openapi: 3.0.4
info:
  title: CashControl Ausgabe API
  version: 1.0.0
  description: REST-API für Ausgaben (AusgabeController)
servers:
  - url: http://localhost:8080
    description: Lokaler Server

tags:
  - name: AusgabeController
    description: Endpoints für Ausgaben

paths:
  /api/v1/ausgabe:
    get:
      tags: [AusgabeController]
      operationId: getAllAusgabe
      summary: Alle Ausgaben
      responses:
        '200':
          description: Alle Ausgaben gefunden
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AusgabeDto'
    post:
      tags: [AusgabeController]
      operationId: createAusgabe
      summary: Neue Ausgabe erfassen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AusgabeDto'
      responses:
        '201':
          description: Ausgabe erfasst (ID im Response-Body)
          content:
            text/plain:
              schema:
                type: string
                description: ID der neu erstellten Ausgabe

  /api/v1/ausgabe/{id}:
    get:
      tags: [AusgabeController]
      operationId: getAusgabeById
      summary: Ausgabe finden mit ID
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Ausgabe mit ID gefunden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AusgabeDto'
        '404':
          description: Ausgabe nicht gefunden
    delete:
      tags: [AusgabeController]
      operationId: deleteAusgabeById
      summary: Ausgabe löschen mit ID
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Ausgabe mit ID gelöscht
        '404':
          description: Ausgabe nicht gefunden
    put:
      tags: [AusgabeController]
      operationId: updateAusgabe
      summary: Ausgabe aktualisieren
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AusgabeDto'
      responses:
        '200':
          description: Ausgabe aktualisiert (kein Response-Body)
        '404':
          description: Ausgabe nicht gefunden

components:
  schemas:
    AusgabeDto:
      title: Zahlung
      type: object
      description: Datentransferobjekt einer Ausgabe
      properties:
        id:
          type: string
          description: Technische ID (bei Create optional)
          example: "a8f1c7d2-1b3e-4f0a-97f9-1b1e9f6b5c2a"
        version:
          type: integer
          format: int64
          description: Version für Optimistic Locking (optional)
          example: 3
        datum:
          type: string
          format: date
          description: Buchungs-/Belegdatum
          example: "2025-08-15"
        empfaenger:
          type: string
          description: Empfänger/Payee
          example: "Coop"
        kategorie:
          $ref: '#/components/schemas/AusgabeKategorieDto'
        text:
          type: string
          description: Beschreibung/Notiz
          example: "Wocheneinkauf"
        betrag:
          type: number
          description: Betrag (positiv für Ausgaben)
          example: 86.45
      required:
        - datum
        - empfaenger
        - kategorie
        - text
        - betrag

    AusgabeKategorieDto:
      type: string
      description: Kategorie der Ausgabe
      enum:
        - VERKEHR_AUTO_TRANSPORT
        - HAUSHALT
        - FERIEN
        - KOMMUNIKATION_MEDIEN
        - GESUNDHEIT
        - PERSOENLICHE_AUSGABEN
        - SPAREN_VORSORGE
        - STEUERN
        - DIVERSES
