spring:
  application:
    name: cashcontrol-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cashcontrol
    username: cashcontrol
    password: secret
  flyway:
    locations: classpath:db/migration/
    clean-on-validation-error: false
    default-schema: cashcontrol
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate    # validiert das Schema mit den Entities beim Starten der Applikation
server:
  port: 8080
  servlet:
    context-path: /cash-control
  compression:
    enabled: true

logging:
  pattern:
    level: '[%X{correlationId}] %5p'
  level:
    ch.reinhard: INFO
#    org.flywaydb: DEBUG


